version: "3.8"

services:
  db:
    container_name: "db"
    build: docker/db
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_HOST: root
      MYSQL_ROOT_PASSWORD: root
    expose:
      - '3306'
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - local-net
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '10'
  api:
    links:
      - db
    container_name: "api"
    build: ./docker/api
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src
    networks:
      - local-net
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '10'
networks:
  local-net:
    driver: bridge